import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url'; // Import fileURLToPath
import csv from 'csv-parser';
import { createClient } from '@sanity/client';
import fetch from 'node-fetch'; // Import node-fetch

const currentDir = path.dirname(fileURLToPath(import.meta.url)); // Use fileURLToPath for correct path resolution

const SANITY_PROJECT_ID = process.env.SANITY_PROJECT_ID || 'g2pb2hqo';
const SANITY_DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET || 'production';
const SANITY_TOKEN = process.env.SANITY_TOKEN || 'skWTHwkl0MbZDphvdPQTdCEihWmrdvXO1ujsBCaz9RQmB6vVRF5i9pHBdzI645sSSSjtoyTx1M7VNSa3KuHZmIaCUzSfom9eko6i2vHaiQYCJRWa1GTQx7scm4OjriJk4Fs8WInesVRfdDRRDdjwW0vk0oWbomnVK6LZ02dyKUUB3g133IPr';
if (!SANITY_PROJECT_ID || !SANITY_TOKEN) {
  console.error('Missing SANITY_PROJECT_ID or SANITY_WRITE_TOKEN environment variables.');
  process.exit(1);
}

const client = createClient({
  projectId: SANITY_PROJECT_ID,
  dataset: SANITY_DATASET,
  apiVersion: '2023-03-20', // Use a recent date
  token: SANITY_TOKEN,
  useCdn: false,
});

const importCsv = async (filePath, documentType, transformFunction) => {
  const results = [];
  return new Promise((resolve, reject) => {
    fs.createReadStream(filePath)
      .pipe(csv())
      .on('data', (data) => results.push(data))
      .on('end', async () => {
        console.log(`Importing ${results.length} ${documentType}s...`);
        const transaction = client.transaction();

        const idMap = {}; // To store mappings between old IDs and new Sanity IDs if needed

        for (const [index, row] of results.entries()) {
          console.log(`Processing ${documentType} ${index + 1}/${results.length}...`);
          try {
            const sanityDoc = await transformFunction(row, idMap); // Await transformFunction
            if (sanityDoc) {
              transaction.createOrReplace(sanityDoc);
            }
          } catch (error) {
            console.error(`Error transforming row for ${documentType}:`, row, error);
          }
        }

        try {
          const commit = await transaction.commit();
          console.log(`Successfully imported ${documentType}s.`, commit);
          // Update idMap with actual Sanity IDs after commit if needed, or if IDs are generated by Sanity.
          // For this script, we assume _id is explicitly set in transformFunction for createOrReplace.
          resolve(idMap);
        } catch (error) {
          console.error(`Error committing transaction for ${documentType}:`, error);
          reject(error);
        }
      })
      .on('error', (error) => {
        console.error(`Error reading CSV file ${filePath}:`, error);
        reject(error);
      });
  });
};

// --- Transformation Functions ---

const transformCategory = (row) => {
  if (!row.id || !row.name || !row.slug) {
    console.warn('Skipping category due to missing required fields:', row);
    return null;
  }
  return {
    _id: row.id,
    _type: 'category',
    name: row.name,
    slug: { _type: 'slug', current: row.slug },
  };
};

const transformSubcategory = (row, idMap) => {
  if (!row.id || !row.name || !row.slug || !row.category_id) {
    console.warn('Skipping subcategory due to missing required fields:', row);
    return null;
  }
  const categoryRef = idMap.categories && idMap.categories[row.category_id] ?
                      { _type: 'reference', _ref: idMap.categories[row.category_id] } :
                      { _type: 'reference', _ref: row.category_id }; // Fallback to original ID if not mapped

  return {
    _id: row.id,
    _type: 'subcategory',
    name: row.name,
    slug: { _type: 'slug', current: row.slug },
    category: categoryRef,
  };
};

const transformProduct = async (row, idMap) => {
  if (!row.id || !row.name || !row.slug || !row.price || !row.category_id) {
    console.warn('Skipping product due to missing required fields:', row);
    return null;
  }

  const categoryRef = idMap.categories && idMap.categories[row.category_id] ?
                      { _type: 'reference', _ref: idMap.categories[row.category_id] } :
                      { _type: 'reference', _ref: row.category_id }; // Fallback
  
  let subcategoryRef = null;
  if (row.subcategory_id && idMap.subcategories && idMap.subcategories[row.subcategory_id]) {
    subcategoryRef = { _type: 'reference', _ref: idMap.subcategories[row.subcategory_id] };
  } else if (row.subcategory_id) {
    subcategoryRef = { _type: 'reference', _ref: row.subcategory_id }; // Fallback
  }

  // Handle images: download and upload to Sanity
  const sanityImages = [];
  if (row.images) {
    let imageUrls = [];
    try {
      imageUrls = JSON.parse(row.images).map(url => url.trim()).filter(Boolean);
    } catch (e) {
      console.warn(`Could not parse images JSON for product ${row.id}: ${row.images}. Error: ${e.message}`);
      imageUrls = row.images.split(',').map(url => url.trim()).filter(Boolean); // Fallback to comma-separated if JSON fails
    }

    for (const url of imageUrls) {
      try {
        console.log(`Downloading image from: ${url}`);
        const response = await fetch(url);
        if (!response.ok) {
          throw new Error(`Failed to download image from ${url}: ${response.statusText}`);
        }
        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer); // Convert ArrayBuffer to Buffer
        
        const asset = await client.assets.upload('image', buffer, {
          filename: path.basename(new URL(url).pathname),
        });
        sanityImages.push({
          _key: `image-${asset._id.replace('image-', '')}-${Math.random().toString(36).substring(7)}`, // Generate a unique key
          _type: 'image',
          asset: {
            _type: 'reference',
            _ref: asset._id,
          },
        });
        console.log(`Uploaded image asset: ${asset._id}`);
      } catch (error) {
        console.error(`Error processing image ${url}:`, error);
      }
    }
  }

  // Handle colors (assuming comma-separated strings in CSV)
  const colors = row.colors ? row.colors.split(',').map(color => color.trim()) : [];

  // Basic Portable Text conversion for detailed_description
  const detailed_description = row.detailed_description ? [
    {
      _key: 'block-1',
      _type: 'block',
      children: [{
        _key: 'span-1',
        _type: 'span',
        marks: [],
        text: row.detailed_description,
      }],
      markDefs: [],
      style: 'normal',
    },
  ] : [];

  return {
    _id: row.id,
    _type: 'product',
    name: row.name,
    slug: { _type: 'slug', current: row.slug },
    price: parseFloat(row.price),
    original_price: row.original_price ? parseFloat(row.original_price) : undefined,
    images: sanityImages,
    description: row.description || undefined,
    detailed_description: detailed_description,
    colors: colors,
    is_featured: row.is_featured === 'true',
    is_ceo_chair: row.is_ceo_chair === 'true',
    is_molded: row.is_molded === 'true',
    is_gaming_chair: row.is_gaming_chair === 'true',
    is_dining_chair: row.is_dining_chair === 'true',
    is_visitor_sofa: row.is_visitor_sofa === 'true',
    is_study_chair: row.is_study_chair === 'true',
    is_outdoor_furniture: row.is_outdoor_furniture === 'true',
    is_folding_furniture: row.is_folding_furniture === 'true',
    show_in_office: row.show_in_office === 'true',
    category: categoryRef,
    subcategory: subcategoryRef,
  };
};

// Skipping transformOrderItem and transformOrder as they are no longer used
const transformOrderItem = () => null; // Placeholder
const transformOrder = () => null; // Placeholder


const runImport = async () => {
  console.log("Starting data import to Sanity...");

  const categoriesIdMap = await importCsv(
    path.join(currentDir, 'categories_rows.csv'),
    'category',
    transformCategory
  );
  idMap.categories = categoriesIdMap;

  const subcategoriesIdMap = await importCsv(
    path.join(currentDir, 'subcategories_rows.csv'),
    'subcategory',
    transformSubcategory
  );
  idMap.subcategories = subcategoriesIdMap;

  await importCsv(
    path.join(currentDir, 'products_rows (1).csv'),
    'product',
    async (row) => await transformProduct(row, idMap)
  );

  // Skipping order items and orders as requested for now.
  console.log("Skipping orders and order items as requested.");

  console.log("Data import complete!");
};

const idMap = {}; // Global map to store IDs for reference resolution

runImport().catch(console.error);
